name: "Deploying to Production"

on:
  push:
    brances:
      - main
jobs:
  Frontend_Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Deploying the frontend"
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{secrets.HOST}}
          username: ubuntu
          key: ${{secrets.KEY}}
          script: |
            source: ~/.nvm/nvm.sh
            cd Passmyfiles
            git reset --hard
            git pull
            cd frontend
            docker stop passmyfile-frontend
            docker rm  passmyfile-frontend
            docker build -t passmyfile-frontend .
            docker run -d --name passmyfile-frontend -p 4173:4173 --restart unless-stopped passmyfile-frontend

  Server_Deployment:
    runs-on: ubuntu-latest
    needs: Frontend_Deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploying the server
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{secrets.HOST}}
          username: ubuntu
          key: ${{secrets.KEY}}
          script: |
            source: ~/.nvm/nvm.sh
            cd Passmyfiles
            cd backend
            docker-build -t passmyfile-server . --no-cache
            docker-compose down
            docker-compose up -d
